In [ ]:
# Filtering Anomalies
# Dataset: Nigerian Economics Data
# Scenario: The governments wants to calculate the average income of working-age adults.
# Reason: They need to set a new minimum wage

In [1]:
# Package of interest
import pandas as pd

In [4]:
# Load our dataset into a dataframe
economic_data = pd.read_csv('/kaggle/input/datasets/awofiranyejames/nigerian-economic-data/nigeria_economic_data.csv')
economic_data.head(25)

,Individual_ID,Age,Gender,Region,Location,Education_Level,Occupation,Employment_Type,Monthly_Income_NGN,Poverty_Status
0,8a61ea0b,6,Female,South East,Urban,Primary,Student,Not in Labor Force,0.00,1
1,dda4058f,46,Male,South West,Urban,Primary,Trade/Services,Informal,35516.10,1
2,a77f8728,50,Female,North West,Rural,Primary,Agriculture,Informal,49952.97,1
3,77530bfc,64,Male,South East,Rural,Secondary,Trade/Services,Self-employed,41902.41,1
4,fdbccc7a,4,Male,North East,Rural,NaN,NaN,Not in Labor Force,0.00,1
5,7a556ab5,13,Male,North Central,Rural,NaN,Student,Not in Labor Force,0.00,1
6,d865955e,10,Male,South West,Rural,NaN,Student,Not in Labor Force,0.00,1
7,8a99565d,33,Male,South West,Urban,NaN,Informal,Informal,129828.67,0
8,e5f96099,45,Male,South West,Urban,Primary,Trade/Services,Informal,54822.91,1
9,9ea600aa,60,Male,South West,Urban,Secondary,Informal,Self-employed,125243.83,0
10,14250841,8,Male,North West,Urban,Primary,Student,Not in Labor Force,0.00,1
11,f0115bdf,70,Female,North Central,Rural,NaN,Agriculture,Informal,53994.74,1
12,cd5ea9de,31,Male,South West,Urban,Secondary,Informal,Self-employed,142881.68,0
13,806dd630,2,Female,North East,Rural,NaN,NaN,Not in Labor Force,0.00,1
14,024fdb1c,11,Male,North East,Rural,NaN,Student,Not in Labor Force,0.00,1
15,c7ff3e4c,3,Female,North West,Rural,NaN,NaN,Not in Labor Force,0.00,1
16,92b14092,8,Female,North Central,Urban,Primary,Student,Not in Labor Force,0.00,1
17,f701b470,25,Male,South South,Urban,Secondary,Trade/Services,Self-employed,121326.17,0
18,6f69545a,36,Male,North East,Rural,NaN,Agriculture,Informal,33422.71,1
19,cee0ae75,3,Female,North Central,Rural,NaN,NaN,Not in Labor Force,0.00,1
20,954d0571,31,Female,South West,Urban,Primary,Informal,Informal,85045.36,1
21,65fe0d9e,7,Male,North West,Rural,Primary,Student,Not in Labor Force,0.00,1
22,62398278,13,Male,South South,Urban,Secondary,Student,Not in Labor Force,0.00,1
23,abe9d6ea,10,Female,North East,Urban,NaN,Student,Not in Labor Force,0.00,1
24,491d7217,48,Female,South South,Rural,Primary,Informal,Informal,37174.10,1

In [3]:
# Scope & Focus
# Remove logical impossibilities
# Targeted slicing
# We must create a new dataset, but only keep rows where Age is 18 or older
adult_only_eco_data = economic_data[(economic_data['Age'] >= 18) & (economic_data['Age'] <= 65)]

In [5]:
adult_only_eco_data.head()
#adult_only_eco_data.shape

,Individual_ID,Age,Gender,Region,Location,Education_Level,Occupation,Employment_Type,Monthly_Income_NGN,Poverty_Status
1,dda4058f,46,Male,South West,Urban,Primary,Trade/Services,Informal,35516.10,1
2,a77f8728,50,Female,North West,Rural,Primary,Agriculture,Informal,49952.97,1
3,77530bfc,64,Male,South East,Rural,Secondary,Trade/Services,Self-employed,41902.41,1
7,8a99565d,33,Male,South West,Urban,NaN,Informal,Informal,129828.67,0
8,e5f96099,45,Male,South West,Urban,Primary,Trade/Services,Informal,54822.91,1

In [6]:
print(f"Original Dataset Size:", len(economic_data))
print(f"New Dataset Size:", len(adult_only_eco_data))

Original Dataset Size: 10000
New Dataset Size: 4923

In [ ]:
**Subsetting for a specific goal

*Dataset: Nigerian Nursing Mothers Dataset

*Scenario:

- You are a non-profit organization

- The NGO has a limited budget

- They want to use ML to understand the health challenges faced by the poorest mothers living in rural areas.

- They need to send in doctors

In [10]:
# Dataset of interest
health_data = pd.read_csv('/kaggle/input/datasets/awofiranyejames/nigerian-nursing-mother-health-care/nigeria_nursing_mothers_healthcare.csv')
health_data.head(3)

,Geopolitical_Zone,Residence,Wealth_Quintile,Education_Level,Skilled_Birth_Attendance,Facility_Delivery,Exclusive_Breastfeeding,Full_Immunization,Distance_to_Facility_km
0,North East,Rural,Middle,Primary,1,1,1,0,9.35
1,South East,Urban,Richest,Higher,1,1,1,1,1.99
2,North Central,Urban,Richer,Primary,1,1,0,0,0.95

In [8]:
health_data['Wealth_Quintile'].unique()

array(['Middle', 'Richest', 'Richer', 'Poorest', 'Poorer'], dtype=object)

In [13]:
# We need to create a new dataset from the existing one
# Poorest & Rural
targeted_mothers = health_data[(health_data['Residence'] == 'Rural') & (health_data['Wealth_Quintile'] == 'Poorest')]

In [14]:
print(f"Original Dataset Size:", len(health_data))
print(f"New Dataset Size:", len(targeted_mothers))

Original Dataset Size: 10000
New Dataset Size: 1866

**Investigating Suspicious Data

*Dataset: Nigerian Unemployment Data

*Scenario: Find suspicious data that needs human review

In [16]:
# Dataset of interest
unemployment_data = pd.read_csv('/kaggle/input/datasets/awofiranyejames/nigeria-unemployment-dataset/nigeria_unemployment_missing_data.csv')
unemployment_data.head(2)

,Age,Gender,Region,Location,Education_Level,Employment_Status,Years_Of_Experience,Monthly_Income_NGN
0,53,Male,North West,Urban,NaN,Employed,37.0,84220.84
1,43,Female,South West,Urban,Primary,Employed,24.0,69911.72


1. Focus: Age and Educational level
2. Is it impossible to have a university degree at 16? No, but it is highly unusual
3. Let's filter to find anyone under 18 who claims to have a university degree

In [17]:
unemployment_data['Education_Level'].unique()

array([nan, 'Primary', 'Secondary', 'Tertiary'], dtype=object)

In [18]:
suspicious_data = unemployment_data[(unemployment_data['Age'] < 18) & (unemployment_data['Education_Level'] == 'Tertiary')]

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [19]:
print(f"Number of Suspicious Records Found:", len(suspicious_data))

Number of Suspicious Records Found: 52