**Introduction to Data Governance**

- The Big Difference: Data Governance vs. Data Management

- The Pillars of Data Governance

- Data Wrangling: Chopping, Cleaning, and Peeling your ingredients

- Machine Learning: Using a high-tech oven

- Data Governance: It is the restaurants food safety code

- Data Governance prevents you from misbehaving with data

*The Big Difference*

- Data Management: Writing Python code, Cleaning data, building a pipeline, exploring the data

- Data Governance: This is a strategic framework.

- With Data Governance: We define who is allowed to touch data, what that data can be used for, how the data quality is monitored, and how long are you allowed to keep the data before throwing it away.

*The Six Pillars of Data Governance*

- Accountability: The designated owner or data steward

- Transparency: You must clearly explain to your customers and regulators what data you are holding, where it came from, how it flows through your pipeline...

- Data Quality: Standards for accuracy, consistency & completeness.

- Security: This controls who has specific access to data.

- Purpose Limitation: Using data for a specific purpose. If it must be repurposed, there must be explicit consent granted.

- Data Retention: You cannot keep customer data forever. Governance defines strict expiration date for data categories.

**Introduction to Inferential Statistics**

- A spoonful of soup is used to make decision about the entire pot of soup.

*Descriptive Statistics:* Simply stating the facts about the data in front of you

*Inferential Statistics:* It is the science using small sample data to draw reliable and mathematically backed Conclusion about the much larger population.


*The median age of the Nigerian population is approximately 18.3 years*

*The median age of the United States population is 39.4 years old*

**Why is Inferential Statistics the Backbone of Machine Learning?**

- Feature Selection: If you have 50 columns in a dataframe, which one will affect your desired outcome, and which ones will be useless? Inferential tests

- A/B Testing: It is a standard for verifying differences between two activities/situations/experiences. Inferential statistics gives us the math to prove relevance.

- Model Validation: Did the 1% improvement of a model mean that the code was smarter or the computer got lucky? Hypothesis testing is used to confirm if performance is genuine or due to luck.

**Four Pillars**

- The Population vs. The Sample: The population is the entire group you want to study. The Sample is a smaller slice of the population

- The Null Hypothesis(H0) vs. The Alternative Hypothesis(Ha): "A defendant is innocent until proven guilty", "The defendant is guilty and it can be proven beyond a reasonable doubt"

- The p-value: The p-value is a number between 0 and 1 that measures the probability that a result is a complete fluke. "If the p-value is low(usually less than 0.05), the null hypothesis must go.

- Confidence Intervals: This a mathematical net designed to capture the true population average with a level of certainty.

**Hands-on Walkthrough**

- United States Educational System

- Case Study: Do Public & Private School Have Different Graduation Rates?

In [6]:
# import packages
import pandas as pd
import numpy as np
from scipy import stats

In [7]:
pd.set_option('display.max_columns', None)
#display(us_edu_data.head())

In [8]:
# dataset of interest
us_edu_data = pd.read_csv('/kaggle/input/datasets/awofiranyejames/us-dataset/us_education_system_dataset.csv')
us_edu_data.head()

,institution_id,institution_name,state_code,state_name,county,nces_locale,level,control,title_i_status,total_enrollment,number_of_teachers,student_teacher_ratio,percent_free_reduced_lunch,racial_white_pct,racial_black_pct,racial_hispanic_pct,racial_asian_pct,racial_native_pct,racial_two_or_more_pct,special_education_pct,english_learner_pct,per_pupil_expenditure_usd,federal_funding_pct,state_funding_pct,local_funding_pct,math_proficiency_pct,reading_proficiency_pct,graduation_rate_pct,chronic_absenteeism_pct,avg_sat_score,avg_act_score,ap_ib_participation_pct,postsecondary_enrollment_pct,stem_certified_flag,broadband_access_pct
0,US-EDU-10001,Jefferson Elementary School,MA,Massachusetts,Central County,Suburban - Midsize,Elementary School,Public,Title I Schoolwide,447,30,14.8,48.9,70.9,2.4,15.4,8.1,0.1,3.1,14.4,12.9,12840,15.0,54.8,30.2,58.3,58.1,80.9,18.0,NaN,NaN,NaN,NaN,No,91.6
1,US-EDU-10002,Lakeshore Middle School,FL,Florida,Miami-Dade County,Suburban - Midsize,Middle School,Private Religious,Not Applicable,293,29,10.0,1.2,34.7,8.6,36.1,13.3,1.3,6.0,13.7,19.3,17009,0.0,2.0,98.0,84.8,98.0,93.5,17.8,NaN,NaN,NaN,NaN,No,94.4
2,US-EDU-10003,Meadowbrook Elementary Academy,TX,Texas,Bexar County,City - Large,Elementary School,Private For-Profit,Not Applicable,315,17,18.2,36.0,26.2,29.2,22.9,12.3,1.9,7.5,15.7,11.3,15374,10.7,55.5,33.8,54.6,66.2,80.2,19.5,NaN,NaN,NaN,NaN,No,94.0
3,US-EDU-10004,Roosevelt Primary School,FL,Florida,Palm Beach County,Suburban - Large,Elementary School,Public,Not Title I Eligible,389,34,11.3,15.1,49.2,16.7,4.3,26.4,0.1,3.3,13.8,9.8,17065,6.8,38.3,54.9,66.1,70.5,82.1,20.5,NaN,NaN,NaN,NaN,No,96.4
4,US-EDU-10005,Highland Park Primary School,MI,Michigan,Macomb County,Suburban - Large,Elementary School,Public,Title I Targeted,397,29,13.9,45.6,78.1,3.2,8.0,3.9,2.1,4.7,19.8,5.3,16823,15.0,42.3,42.7,54.6,46.7,90.2,19.9,NaN,NaN,NaN,NaN,No,86.3

In [9]:
us_edu_data.shape

(5000, 35)

**The Independent T-Test**

*We are comparing two independent averages.*

- "Are the average values of two independent groups different enough that we should believe the difference is real?"

- We are comparing two separate groups: people, customers, patients, students, etc

*Scenario:* The company launches a new training program

- They want to know: Do people who receive the new training score differently from people who receive the old training?

- Group A -> Old Training

- Group B -> New Training

*Stats for old & new training:*

- Old Training: 65, 70, 72, 68, 75, 71, 69

- New Training: 78, 82, 80, 85, 79, 83, 81

*The Data Science Question:*

- Is the difference large enough for HR to believe the new training actually make a difference?

*This is where the Independent T-Test comes in*

- Different People are tested - Independent t-test
- Same People are tested twice - paired t-test

In [10]:
# Simulate a realistic example
# We are testing whether a new marketing campaign increases customer spending

np.random.seed(42)

In [11]:
control = np.random.normal(loc=500, scale=100, size=100)
treatment = np.random.normal(loc=550, scale=100, size=100)
# Control -> Customers who did not receive the campaign
# Treatment -> Customers who received the campaign

In [12]:
control.mean()

np.float64(489.61534826059057)

In [13]:
treatment.mean()

np.float64(552.2304587049924)

In [14]:
# Control: 506
# Treatment: 560

In [15]:
# The Difference
difference = treatment.mean() - control.mean()

In [16]:
difference

np.float64(62.615110444401864)

In [17]:
# The treament group spent approximately $54 more than the control group
# Is $54 enough evidence that the campaign really works?

In [18]:
# Run an Independent T-Test
from scipy.stats import ttest_ind

In [19]:
t_stat, p_value = ttest_ind(treatment, control)

In [20]:
print("t-statistic:", t_stat)
print("p-value:", p_value)

t-statistic: 4.754695943505295
p-value: 3.819135262679223e-06

In [21]:
# The Incorrect Analysis
# "There is a 0.01% probability that the null hypothesis is True"

# The Correct Analysis
# If there really were no difference between the two groups,
# getting a difference this large would be unusual

# There is a strong evidence that the groups differ
# The campaign has a significant difference in customer spending

In [22]:
# The US Educational Data
# Do the Public & Private Non-Profit Schools have different graduation rates

In [23]:
us_edu_data['control'].unique()

array(['Public', 'Private Religious', 'Private For-Profit',
       'Public Charter', 'Private Non-Profit'], dtype=object)

In [24]:
# Null Hypothesis: There isn't any difference in their graduate rates

In [25]:
public_grads = us_edu_data[us_edu_data['control'] == 'Public']['graduation_rate_pct']

In [26]:
private_grads = us_edu_data[us_edu_data['control'] == 'Private Non-Profit']['graduation_rate_pct']

In [27]:
# Run the Independent T-Test
t_stat, p_value = ttest_ind(public_grads, private_grads)

In [28]:
print(f"Calculated T-Statistics: {t_stat:.4f}")
print(f"Calculated p-value: {p_value:.4f}")

Calculated T-Statistics: -12.0869
Calculated p-value: 0.0000

In [29]:
# Interpret the result for our stakeholder
alpha = 0.05

In [30]:
if p_value < alpha:
  print("Result: Significant! We reject the Null Hypothesis. There is a real difference.")
else:
  print("Result: Not significant. We fail to reject the Null. Any difference was just a fluke.")

Result: Significant! We reject the Null Hypothesis. There is a real difference.

In [31]:
public_grads.mean()

np.float64(84.40451085424301)

In [32]:
private_grads.mean()

np.float64(87.83086172344689)

**One-Way ANOVA - Comparing Multiple Groups**

*The Relatable Analogy: The Tomato Factory*

- Testing three brands of tomato fertilizer

- Brand A, Brand B, & Brand C - Which one makes the plants grow the tallest.

- Why don't we run three separate t-tests?

- Statistical Exhaustion - Run three t-tests back-to-back, our overall chance of making mistakes increases.

*The Analysis of Variance:* It checks all the groups simultaneously. Is there any statistically significant differences among these averages, or are they the same?

In [33]:
# Data
us_edu_data.head(3)

,institution_id,institution_name,state_code,state_name,county,nces_locale,level,control,title_i_status,total_enrollment,number_of_teachers,student_teacher_ratio,percent_free_reduced_lunch,racial_white_pct,racial_black_pct,racial_hispanic_pct,racial_asian_pct,racial_native_pct,racial_two_or_more_pct,special_education_pct,english_learner_pct,per_pupil_expenditure_usd,federal_funding_pct,state_funding_pct,local_funding_pct,math_proficiency_pct,reading_proficiency_pct,graduation_rate_pct,chronic_absenteeism_pct,avg_sat_score,avg_act_score,ap_ib_participation_pct,postsecondary_enrollment_pct,stem_certified_flag,broadband_access_pct
0,US-EDU-10001,Jefferson Elementary School,MA,Massachusetts,Central County,Suburban - Midsize,Elementary School,Public,Title I Schoolwide,447,30,14.8,48.9,70.9,2.4,15.4,8.1,0.1,3.1,14.4,12.9,12840,15.0,54.8,30.2,58.3,58.1,80.9,18.0,NaN,NaN,NaN,NaN,No,91.6
1,US-EDU-10002,Lakeshore Middle School,FL,Florida,Miami-Dade County,Suburban - Midsize,Middle School,Private Religious,Not Applicable,293,29,10.0,1.2,34.7,8.6,36.1,13.3,1.3,6.0,13.7,19.3,17009,0.0,2.0,98.0,84.8,98.0,93.5,17.8,NaN,NaN,NaN,NaN,No,94.4
2,US-EDU-10003,Meadowbrook Elementary Academy,TX,Texas,Bexar County,City - Large,Elementary School,Private For-Profit,Not Applicable,315,17,18.2,36.0,26.2,29.2,22.9,12.3,1.9,7.5,15.7,11.3,15374,10.7,55.5,33.8,54.6,66.2,80.2,19.5,NaN,NaN,NaN,NaN,No,94.0

In [34]:
# Is there a significant difference in the average student-teacher ratio
# across different geographical locales

In [35]:
# Unique locales
us_edu_data['nces_locale'].unique()

array(['Suburban - Midsize', 'City - Large', 'Suburban - Large',
       'Town - Distant', 'Town - Fringe', 'Rural - Remote',
       'Rural - Fringe', 'City - Midsize'], dtype=object)

In [36]:
# Group our student-teacher ratios by Geographic locale
city_ratios = us_edu_data[us_edu_data['nces_locale'] == 'City - Large']['student_teacher_ratio']
suburban_ratios = us_edu_data[us_edu_data['nces_locale'] == 'Suburban - Large']['student_teacher_ratio']
rural_ratios = us_edu_data[us_edu_data['nces_locale'] == 'Rural - Fringe']['student_teacher_ratio']

In [37]:
# Run the One-Way ANOVA Test
f_stat, p_value = stats.f_oneway(city_ratios, suburban_ratios, rural_ratios)

In [38]:
# H0 - Staffing ratios differ significantly across locales
# Ha - Any difference in ratio is just a random fluke

In [39]:
# Interpret Our Result
alpha = 0.05
if p_value < alpha:
  print("Result: Significant! We reject the Null Hypothesis. Staffing ratios differ significantly across locales.")
else:
  print("Result: Not significant. We fail to reject the Null. Any difference was just a fluke.")

Result: Not significant. We fail to reject the Null. Any difference was just a fluke.

**The Chi-Square Test - Connecting Categories**

*The Relatable Analogy: The Movie Theatre Snack Bar*

- Does a customer's choice of snack (popcorn, Fishpie, or Donuts) depend on the movie they are watching (Action vs. Comedy)?

- Snack choice and the movie type

- A Chi-Square Test of Independence: Whether the snack choice is independent of the movie type, or if there is a strong, non-random connection

In [40]:
# Real-World Use Case
# Does a school's `title_i_status`have a structural association with its STEM certification status
# `title_i_status`| `stem_certified_flag`

In [41]:
us_edu_data['stem_certified_flag'].unique()

array(['No', 'Yes'], dtype=object)

In [42]:
us_edu_data['title_i_status'].unique()

array(['Title I Schoolwide', 'Not Applicable', 'Not Title I Eligible',
       'Title I Targeted'], dtype=object)

In [43]:
# Create a contingency table with counts of the categories
contingency_table = pd.crosstab(us_edu_data['title_i_status'], us_edu_data['stem_certified_flag'])

In [44]:
contingency_table

stem_certified_flag     No  Yes
title_i_status
Not Applicable         930  178
Not Title I Eligible   664  103
Title I Schoolwide    1841  339
Title I Targeted       813  132

In [45]:
# Run the Chi-Test of Independence
chi2_stat, p_value, dof, expected = stats.chi2_contingency(contingency_table)

In [46]:
print(p_value)

0.288224016178402

In [47]:
# Ho - STEM certification is structurally associated with Title I eligibility
# Ha - STEM certification is independent of Title I funding status.
# Interpret
alpha = 0.05
if p_value < alpha:
  print("Result: Significant! We reject the Null Hypothesis. STEM certification is associated with Title I eligibility.")
else:
  print("Result: Not significant. We fail to reject the Null.")

Result: Not significant. We fail to reject the Null.

**Correlation Coefficient Significance - The Smoking Gun**

*The Relatable Analogy: Height vs. Weight*

- The correlation coefficient(r) elegantly condenses the complex scatterplot into a single number between -1 & 1

- What if we calculate a correlation of r =.4 on a tiny sample of data? Is that real? or is it just happenstance?

- We must calculate the standard error or our correlation to test the Null Hypothesis

In [48]:
# `per_pupil_expenditure_usd`
# `graduation_rate_pct`
# Does the school's per_pupil_expenditure_usd correlate with its graduation_rate_pct
# Testing the significance of the correlation coefficient

In [49]:
grad_rate = us_edu_data['graduation_rate_pct']
spending = us_edu_data['per_pupil_expenditure_usd']

In [50]:
grad_rate.head()

0    80.9
1    93.5
2    80.2
3    82.1
4    90.2
Name: graduation_rate_pct, dtype: float64

In [51]:
spending.head()

0    12840
1    17009
2    15374
3    17065
4    16823
Name: per_pupil_expenditure_usd, dtype: int64

In [52]:
# Pearson Correlation Coefficient
r_coeff, p_value = stats.pearsonr(grad_rate, spending)

In [53]:
print(f"Calculated Correlation Coefficient: {r_coeff:.4f}")
print(f"Calculated p-value: {p_value:.4f}")

Calculated Correlation Coefficient: 0.1997
Calculated p-value: 0.0000

In [54]:
# Interpret
alpha = 0.05
if p_value < alpha:
  print("Result: Significant! There is a real correlation.")
else:
  print("Result: Not significant. Any correlation was just a coincidence.")

Result: Significant! There is a real correlation.